image: python:latest

stages:
  - verification
  - tests
  - build

verification:
  stage: verification
  script:
    - python --version
    - whoami

run_tests:
  stage: tests
  script:
    - apk add postgresql-dev --no-cache
    - pip install psycopg2-binary
    - pip install -r requirements.txt
    - python tests/basic.py

build:
  stage: build
  script:
    - apk add postgresql-dev --no-cache
    - pip install psycopg2-binary
    - pip install -r requirements.txt